version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: notemesh-postgres
    environment:
      POSTGRES_USER: notemesh
      POSTGRES_PASSWORD: notemesh_password
      POSTGRES_DB: notemesh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notemesh-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notemesh -d notemesh"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: notemesh-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notemesh-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notemesh-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://notemesh:notemesh_password@postgres:5432/notemesh
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: your-production-secret-key-change-this
      DEBUG: "false"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - notemesh-network
    volumes:
      - ./backend:/app
      - /app/src/notemesh/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  notemesh-network:
    driver: bridge