"""Add HttpUrlListType converter for hyperlinks

Revision ID: 0142f314ad72
Revises: 4e702a2d2f86
Create Date: 2025-09-14 05:21:45.975807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0142f314ad72'
down_revision: Union[str, Sequence[str], None] = '4e702a2d2f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
