name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      NOTEMESH_SKIP_LIFESPAN_DB: "1"
      PYTHONPATH: backend/src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            backend/requirements.txt
            backend/requirements-dev.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        working-directory: backend
        run: pytest -q

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: backend/htmlcov
          if-no-files-found: ignore

      # Non-blocking quality checks (keep visible but don't fail the build initially)
      - name: Lint (flake8)
        continue-on-error: true
        working-directory: backend
        run: flake8 src/ --max-line-length=100

      - name: Format check (black)
        continue-on-error: true
        working-directory: backend
        run: black --check --line-length=100 src/ tests/

      - name: Import sorting (isort)
        continue-on-error: true
        working-directory: backend
        run: isort --profile=black --check-only src/ tests/

      - name: Type check (mypy)
        continue-on-error: true
        working-directory: backend
        run: mypy src/ --strict
